name: Deploy to Raspberry Pi (Locally)

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # This uses your self-hosted runner on the local machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Modify api.js (replace BASE_URL)
        run: |
          # Use sed to replace "BASE_URL" in api.js with a new value
          sed -i 's|BASE_URL.*|BASE_URL = "https://uccelliapp.duckdns.org/api";|' ./js/api.js

      - name: Deploy to local Nginx directory
        run: |
          # Rsync or cp files directly to the Nginx web directory
          sudo rsync -avz --delete --exclude .git --exclude node_modules ./ /var/www/uccelli-ui/

      - name: Restart Nginx (optional)
        run: |
          sudo systemctl reload nginx
